services:
    postgres:
        image: postgres 
        environment:
            - POSTGRES_PASSWORD=thailand22Thailand22
        ports:
            - 5430:5432
        volumes:
            - pgdata:/var/lib/postgresql/data 
volumes:
    pgdata:

