---
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=thailand22Thailand22
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongopw
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports: 
      - 5672:5672
      - 15672:15672
  auction-svc:
    image: quattroworld/auction-svc:latest
    build: 
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - ASPNETCORE_URLS=http://+:7777
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=thailand22Thailand22;Database=sprawdzone
        - IdentityServiceUrl=http://identity-svc
        - Kestrel__Endpoints__Grpc__Protocols=Http2
        - Kestrel__Endpoints__Grpc__Url=http://+:7777
        - Kestrel__Endpoints__WebApi__Protocols=Http1
        - Kestrel__Endpoints__WebApi__Url=Http://+:80
    ports:
        - 7001:80
        - 7777:7777
    depends_on:
        - postgres
        - rabbitmq
  search-svc:
    image: quattroworld/search-svc:latest
    build: 
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - RabbitMq__Host=rabbitmq
        - ConnectionStrings__MongoDbConnection=mongodb://root:mongopw@mongodb
        - AuctionServiceUrl=http://auction-svc
    ports:
        - 7002:80
    depends_on:
        - mongodb
        - rabbitmq
  identity-svc:
    image: quattroworld/identity-svc:latest
    build: 
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        - ASPNETCORE_URLS=http://+:80
        - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=thailand22Thailand22;Database=identity
    ports:
        - 5000:80
    depends_on:
        - postgres
        - rabbitmq
  gateway-svc:
    image: quattroworld/gateway-svc:latest
    build: 
      context: .
      dockerfile: src/GetewayService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Docker
        - ASPNETCORE_URLS=http://+:80
 
    ports:
        - 6001:80
  bid-svc:
    image: quattroworld/bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__BidDbConnection=mongodb://root:mongopw@mongodb
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - 7003:80
    depends_on:
      - mongodb
      - rabbitmq
  notify-svc:
    image: quattroworld/notify-svc:latest
    build:
      context: .
      dockerfile: src/NotficationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - 7004:80
    depends_on:
      - rabbitmq
  web-app:
    image: quattroworld/web-app
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    volumes:
      - /var/lib/web/data
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://identity-svc
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
volumes:
  pgdata:
  mongodata: