services:
    postgres:
        image: postgres 
        environment:
            - POSTGRES_PASSWORD=thailand22Thailand22
        ports:
            - 5430:5432
        volumes:
            - /var/lib/postgresql/data 
    mongodb:
        image: mongo
        environment:
           - MONGO_INITDB_ROOT_USERNAME=root
           - MONGO_INITDB_ROOT_PASSWORD=mongopw
        ports:
           - 27017:27017
        volumes:
           - /var/lib/mongodb/data
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
           - 5672:5672
           - 8080:15672 


            